### ISSUE TITLE
npm install fails with next 11.1

### ISSUE THREAD

**Issue by jacobdubail** [nextauthjs/react-query#12]
Not sure how I broke it...

```
$ npm install --save @next-auth/react-query

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! While resolving: undefined@undefined
npm ERR! Found: next@11.1.0
npm ERR! node_modules/next
npm ERR!   next@"^11.0.0" from the root project
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^10.0.3" from @next-auth/react-query@0.0.12
npm ERR! node_modules/@next-auth/react-query
npm ERR!   @next-auth/react-query@"*" from the root project
...
```

next 11.1
next-auth 3.29.0
react-query 3.21.1
typescript 4.2.4

**Comment by balazsorban44** [comment]
If I had to guess, you are using `npm@7`, right?

I suggest you have a read: https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies

Happy to take a PR that fixes this though.

**Comment by jacobdubail** [comment]
> If I had to guess, you are using `npm@7`, right?

You guessed it! You would think at this point in my career I would remember to check things like this :/ That fixed it. 
`npm i @next-auth/react-query --legacy-peer-deps `

**Comment by balazsorban44** [comment]
Always assume you know nothing then nothing will surprise you. 😄


Anyway, as mentioned, we could certainly add `11` here: https://github.com/nextauthjs/react-query/blob/8051b76b0353fc6e9e623def745fcf6666d7d966/package.json#L36
