### ISSUE TITLE
Support for Next.js 12 and NextAuth v4

### ISSUE THREAD

**Issue by ffleandro** [nextauthjs/react-query#14]
I'm currently trying to use this library using the following versions of Nextjs and NextAuth, but having the below error:

dependencies:
```
next: 12.0.3
next-auth: 4.0.0-beta.6
node: v14.18.1
typescript: 4.4.4
```

error:
```
> Build error occurred
Error: Dynamic require of "react" is not supported
    at xe (file:///myproject/node_modules/@next-auth/react-query/dist/index.mjs:1:294)
    at file:///myproject/node_modules/@next-auth/react-query/dist/index.mjs:1:39268
    at file:///myproject/node_modules/@next-auth/react-query/dist/index.mjs:1:373
    at file:///myproject/node_modules/@next-auth/react-query/dist/index.mjs:4:497
    at file:///myproject/node_modules/@next-auth/react-query/dist/index.mjs:1:373
    at file:///myproject/node_modules/@next-auth/react-query/dist/index.mjs:4:14209
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24) {
  type: 'Error'
}
```

**Comment by micahbule** [comment]
See https://github.com/nextauthjs/react-query/issues/7#issuecomment-923099050

Even the author suggested that it might be better to implement this as a snippet rather than maintaining it as a module given how small the module is and pretty much straightforward.

**Comment by balazsorban44** [comment]
Yes. Unfortunately, I had to move away from this implementation and thus don't have the time to properly maintain it, but if anyone wants to pick it up, just tell me!

**Comment by joshmedeski** [comment]
@balazsorban44 what do you recommend using now? For those of us that use React Query and Next Auth together.

**Comment by micahbule** [comment]
> @balazsorban44 what do you recommend using now? For those of us that use React Query and Next Auth together.

You can check #7

**Comment by JensMou** [comment]
> Yes. Unfortunately, I had to move away from this implementation and thus don't have the time to properly maintain it, but if anyone wants to pick it up, just tell me!

How does it look now? Or do you have any other suggestions for those using react-query, next-auth@4 and next@12?

**Comment by micahbule** [comment]
Hi @JensMou, as the author suggests in #7, you can just implement this is a snippet instead of maintaining a module for it. Less dependencies means better maintenance. You can literally open this file https://github.com/nextauthjs/react-query/blob/main/index.js, copy the content, and save it as a custom hook in your code base.

I do like to suggest to the author marking this module outdated/deprecated if no one is taking up the offer to take over.

**Comment by JensMou** [comment]
>  You can literally open this file https://github.com/nextauthjs/react-query/blob/main/index.js, copy the content, and save it as a custom hook in your code base.

This has an invalid hook call:
`Error: Invalid hook call. Hooks can only be called inside of the body of a function component`

Also: Does any of you have an example with Typescript?
