### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by kripod** [nextauthjs/react-query#4]
Unfortunately, this module only supports ESM exports, which the ecosystem isn’t yet ready for:

<img width="1057" alt="" src="https://user-images.githubusercontent.com/14854048/115707447-168d7a00-a36f-11eb-88e9-a2fcd74ae01b.png">

**Comment by cryptiklemur** [comment]
Why was this closed?

**Comment by balazsorban44** [comment]
Could not reproduce the problem (tried both Webpack 4 and Webpack 5). If you think it's still an issue, I welcome PRs to fix it!

**Comment by cryptiklemur** [comment]
Try to reproduce with a project using typescript. Im not sure exactly what configs sets up the imports to not mesh together, but this project should probably export es5 and commonjs style, to be compatible with whatever is importing it

**Comment by tobimori** [comment]
Same issue with Typescript 4.2.4 + Webpack 5.

```
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.@next-auth/react-query (/Users/tobimori/Developer/vitals/.next/server/pages/app/sites/[siteId].js:164:18)
    at __webpack_require__ (/Users/tobimori/Developer/vitals/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/app/common/UserAvatar/index.tsx:7:80)
/Users/tobimori/Developer/vitals/node_modules/@next-auth/react-query/index.js:1
import { useQuery } from "react-query"
^^^^^^
```

**Comment by ndom91** [comment]
Okay so I think this is a problem with next.js not supporting ESM correctly yet - I had the same issue with my [`ndom91/react-timezone-select`](https://github.com/ndom91/react-timezone-select) library. Any library with `type: 'module'` will throw the same error. Here's what the guy had to say in my issues when I came across this:

> Having investigated this issue I will leave it up to the package maintainer to determine it is worth an appropriate solution. The reason this happens to NextJS users is because ESM is not the mode that NextJS runs in. This library is in full ESM mode; and assumes import and export are enabled in the implementation side. 
> 
> [Source](https://github.com/ndom91/react-timezone-select/issues/24#issuecomment-826699615)

Theres a next.js module you can install [`https://www.npmjs.com/package/next-transpile-modules`](https://www.npmjs.com/package/next-transpile-modules)

And use like so:

```js
// next.config.js
const withTM = require('next-transpile-modules')(['@next-auth/react-query']);

module.exports = withTM({
  ...
})
```
