### ISSUE TITLE
possible add nextauthjs / react-query in existing react-query ? -  No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by isggwp** [nextauthjs/react-query#7]
I am sory maybe sounds like the questions. I've existing **next auth**, and **react-query**  setup. then  i adding  `/nextauthjs/react-query` lib with
 
```
import { useSession } from "@next-auth/react-query"

const [session, loading] = useSession({
  required: true,
  redirectTo: "/auth/sign-in?error=InvalidSession",
  queryConfig: {
    staleTime: 60 * 60 * 3, // 3 hours
    refetchInterval: 60 * 5 // 5 minutes 
  }
})
```
and i got some error 
`No QueryClient set, use QueryClientProvider to set one`

any or something wrong or need additional setup on my code?

**Comment by balazsorban44** [comment]
could you please provide a reproduction?

we are using it at work with an existing react-query setup

**Comment by Fghurayri** [comment]
Hey @balazsorban44,

Thanks for the tool. I'm facing the same issue. Here is a minimal version to reproduce it:

https://github.com/Fghurayri/repro-nextjs-nextauth-rq-issue

**Comment by liamrohan** [comment]
> Hey @balazsorban44,
> 
> Thanks for the tool. I'm facing the same issue. Here is a minimal version to reproduce it:
> 
> https://github.com/Fghurayri/repro-nextjs-nextauth-rq-issue

Facing the same response, almost identical implementation. Thanks

**Comment by balazsorban44** [comment]
thanks, will have a look

**Comment by vorcigernix** [comment]
Same issue when I just replaced original session from next-auth with code above (no other changes, no react-query implemented).
Edit: leaving for future reference, react query needs to be initialized, it does not work without it. Thanks @balazsorban44 for clarification.

**Comment by balazsorban44** [comment]
without a query client provider, this won't work though! so that's a different issue

**Comment by balazsorban44** [comment]
I did some changes, could someone verify that `0.0.12` fixes the problem? I tested it at work on our application, and this issue went away.
See the changes diff: https://github.com/nextauthjs/react-query/commit/5cdac9409e54ed3f052ed059c90d96e5490877be

**Comment by heteibako** [comment]
Same issue 
<img width="960" alt="Screenshot 2021-06-24 at 19 38 09" src="https://user-images.githubusercontent.com/19397150/123308285-c1631580-d523-11eb-8191-487984117418.png">

**Comment by balazsorban44** [comment]
@heteibako could you please verify the package versions in node_modules and your lock file? also your next version and next config js?

I tried this at work with next 10.x and had no problems!

**Comment by heteibako** [comment]
Will get back to you tomorrow. Maybe I will try to delete the package.json lock file as well.
reverted everything back to the previous state.

**Comment by heteibako** [comment]
What is supposed to be in the `next.config.js`?
I have only this
```
module.exports = {
  dateFormat: {
    locales: ['hu', 'en'],
    defaultLocale: 'hu',
  },
};
```

**Comment by balazsorban44** [comment]
I was just curious. The best thing would be a full reproduction, maybe your repo is public?

**Comment by vorcigernix** [comment]
@balazsorban44 it seems like you can still reproduce it with https://github.com/Fghurayri/repro-nextjs-nextauth-rq-issue

**Comment by Wgil** [comment]
I'm facing the same issue with latest version

**Comment by raymclee** [comment]
same issue

**Comment by raymclee** [comment]
i got below error if i use the useQuery hook and pass fetchSession to it

Unhandled Runtime Error
Error: Dynamic require of "react" is not supported

**Comment by phyolim** [comment]
Same issue here. v0.0.12 nextjs 11.0.1.
Edit: I copied the functions and used exact same way. It works that way. Strange. Not sure what's going on

**Comment by italodeandra** [comment]
This error happens when you have two installations of the same package.

When using `npm` I'm required to use the `--legacy-peer-deps` because `@next-auth/react-query` it doesn't accept the latest Next version, so this might be reason of having duplicate installations of React Query.

For now I did the same as @phyolim. I just stole the `index.js`. This is a simple implementation, it should have been a documentation page instead of an entire library.

**Comment by balazsorban44** [comment]
@italodeandra you might be right. the maintenance overhead almost doesn't worth it having a separate package... copy pasting the index file is probably enough for anyone interested in this. 😬

**Comment by ataschz** [comment]
Hey guys, what's the solution for this issue?

**Comment by bsides** [comment]
Facing the same problem, in the server side. Cliente side shows Unhandled Runtime Error, saying it couldnt require React dynamically

Server (console)
![image](https://user-images.githubusercontent.com/87631/134036130-056b79e5-e13a-4545-977f-b649cafe738f.png)

Client
![image](https://user-images.githubusercontent.com/87631/134035852-da5126ce-688a-4dbb-bc77-02ab3d3f0e47.png)

**Comment by balazsorban44** [comment]
I currently don't have the bandwidth to maintain this package, and given how simple the source code is, it might be a better idea to simply provide it as a snippet in the docs, rather than a package.

Could you copy paste the source code and tell me if the problem goes away? 🙏🙄

**Comment by vexxvakan** [comment]
Just tried it out by just copying the source code -> doesn't work either. Looking into it now, as it behaves really strange imo

Edit: works now, the error was on my behalf!

Anyone trying to get this working with TypeScript: copy the typings from the index.d.ts and add them to your copied source code from this lib. Works absolutely fine!
